config/routes.rb
Rails.application.routes.draw do
  
  root 'alternatives#index'
  
  resources :alternatives, only: [:index, :create, :destroy]
  resources :traits
  resources :analyze
  
  resources :critical_points
  resources :requirements
  resources :evaluations
  resources :critical_evaluations

  devise_for :users, :controllers => { :registrations => "user/registrations", :sessions => "sessions", :invitations => 'invitations'  }
  get 'my_friends', to: 'users#my_friends'
  resources :users, only: [:show] do
    collection do
      get '/:id/propose_critical_points', to: 'critical_points#index', as: 'propose_critical_points'
      get '/:id/propose_requirements', to: 'requirements#index', as: 'propose_requirements'
    end
  end
    
  resources :friendships
  
  resources :requests
  
  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
      get :unread
    end
  end
  
  
  
  get 'show_proposals', to: 'proposals#show'
  
  resources :requests, only: [:index, :create]
  
  get 'welcome', to: 'welcome#start'
  
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
  
  

end

app/models/critical_point.rb
class CriticalPoint < ActiveRecord::Base
  belongs_to :alternative
  belongs_to :point, polymorphic: true
  belongs_to :user
  belongs_to :proposer, :class_name => "User"
  has_many :evaluations, :as => :rateable, dependent: :destroy
  
  def self.proposed_by(user)
    where(proposer: user)
  end
  
  def self.points_of_type(traits)
    self.where(point_type: traits.singularize.capitalize).map { |cp| cp.point }
  end
  
  def already_exists?
    CriticalPoint.exists?(:alternative_id => self.alternative_id, 
                  :point_type => self.point_type, :point_id => self.point_id, 
                  :proposer_id => self.proposer_id, :user_id => self.user_id)
  end

  def alternative_index
    self.user.own_alternatives.index(self.alternative)
  end
end

app/controllers/critical_points_controller.rb
class CriticalPointsController < ApplicationController
  before_filter :require_alternatives_and_mirror
  
  def index
    if params[:proposer_id]
      @user = User.find(params[:proposer_id])
    else
      @user = current_user
    end
    
    user_session.set_showable("critical_points")
    user_session.set_exampleable("basic")
    
    @traits = ["strengths","weaknesses"]
  end
  
  def create
    @critical_point = CriticalPoint.new(critical_point_params)
    @critical_point.user = @critical_point.alternative.user
    
    @critical_point.save unless @critical_point.already_exists?
    
    #Create notification
    Notification.generate("proposed", @critical_point) unless @critical_point.user == current_user
    
    respond_to do |format|
      format.js
    end
  end
  
  def destroy
    @critical_point = CriticalPoint.find(params[:id])
    @alternative = Alternative.find(@critical_point.alternative_id)
    @user = @alternative.user
    @critical_point.destroy
    @traits = ["Strength","Weakness"]
    
    respond_to do |format|
      format.js
    end
  end
  
  private
  
  def critical_point_params
    params.require(:critical_point).permit(:alternative_id, :point_type, :point_id, :proposer_id)
  end
  
  def require_alternatives_and_mirror
    if current_user.own_alternatives.count == 0
      flash[:danger] = "Please state at least one alternative to start working with Critical points"
      redirect_to alternatives_path
    elsif current_user.traits_count == 0
      flash[:danger] = "Please state at least couple of traits to start working with Critical points"
      redirect_to traits_path
    end
  end
end

app/views/critical_points/_counter.html.erb
<h4><span class="label label-primary"><%= alternative.critical_points.proposed_by(user).count %>/7</span></h4>
          

app/views/critical_points/_critical_point.html.erb
<li class="list-group-item <%= critical_point.point.class.to_s.downcase %>-point-style">
  <div class="row">
    <div class="col-md-8 col-sm-6">
      <%= link_to critical_point_path(critical_point), method: :delete, id: "destroy_critical_point",
                  data: { confirm: 'Are you sure you want to delete this critical point and all its evaluations?' },
                  :remote => true, :class => 'close-link destroy_critical_point' do %>
        <span class="fa-stack">
          <i class="fa fa-circle fa-default fa-stack-2x"></i>
          <i class="fa fa-times fa-stack-1x fa-inverse"></i>
        </span>
      <% end %>
      <%= critical_point.point.name %>
    </div>
    
      <div class="col-md-4 col-sm-6 pull-right">
        <%= render partial: 'evaluations/scale', object: 3, :locals => { :showable => critical_point } %>
      </div>
  </div>    
</li>    

app/views/critical_points/_trait.html.erb
  <%= button_to trait.name, { :controller => :critical_points, :action => :create,
            :critical_point => {
              :point_id => trait.id, :point_type => trait.class, 
              :proposer_id => current_user.id, :alternative_id => alternative.id 
            }},
            form_class: "critical-point remove-trait", class: "btn btn-xs #{trait.style}", 
            remote: true %>

app/views/critical_points/_traits.html.erb
<div id="traits-listing-<%= @user.own_alternatives.index(alternative) %>-<%= @traits.index(traits) %>">
  <% @user.not_assigned_to(alternative, traits, current_user).each do |trait| %>
    <div>
      <%= render partial: "trait", object: trait, locals: { :alternative => alternative } %>
    </div>
  <% end %>
</div> 

app/views/critical_points/create.js.erb
$('#critical-points-<%= @critical_point.alternative_index %>').append('<%= j render @critical_point %>');
$('#counter-<%= @critical_point.alternative_index %>').html('<%= j render partial: 'critical_points/counter', locals: { alternative: @critical_point.alternative, user: current_user } %>')
$('.remove-trait').bind('ajax:success', function() {  
        $(this).closest('div').fadeOut();
});  

app/views/critical_points/destroy.js.erb
$('.destroy_critical_point').bind('ajax:success', function() {  
        $(this).closest('li').fadeOut();
});
$('#counter-<%= @critical_point.alternative_index %>').html('<%= j render partial: 'critical_points/counter', locals: { alternative: @critical_point.alternative, user: current_user } %>')
$('#traits-listing-<%= @user.own_alternatives.index(@alternative) %>-<%= @traits.index(@critical_point.point.class.to_s) %>').append('<%= j render partial: "trait", object: @critical_point.point, locals: { :alternative => @alternative } %>');

app/views/critical_points/index.html.erb
<% @user.own_alternatives.each do |alternative| %>
  <div class="panel panel-default">
    <div class="panel-heading clearfix">
      <div class="panel-title">
        <div class="row">
          <div class="col-xs-10 text-left">
            Which of <%= display_name_for(@user) %> traits are critical to <%= alternative.name.downcase %>? How big their impact?
          </div>
          <div class="col-xs-2 text-right" id="counter-<%= @user.own_alternatives.index(alternative) %>">
            <%= render partial: 'critical_points/counter', locals: { alternative: alternative, user: current_user } %>
          </div>
        </div>  
      </div>
    </div>
    <div class="panel-body">
      <% if ( alternative.critical_points.proposed_by(@user).count >= 7 ) && ( @user == current_user )%>
        <ul class="list-group">
        <li class="list-group-item">
          <div class="row">
            <div class="col-md-8 col-sm-8">
              Evaluate alternative regarding stated critical points
            </div>
            <div class="col-md-4 col-sm-4">
              <%= render partial: 'evaluations/critical_scale', locals: { :alternative => alternative, :scale => 4 } %>
            </div>
          </div>
        </li>
      </ul>
      <% end %>
      <ul class="list-group" id="critical-points-<%= @user.own_alternatives.index(alternative) %>">
        <%= render partial: "critical_point", collection: alternative.critical_points.proposed_by(current_user) %>
      </ul>
    </div>   
    <div class="panel-body">
      <div class="row">
        <% @traits.each do |trait| %>  
          <div class="col-md-4 col-xs-6">
            <div class="panel panel-default">
              <div class="panel-heading clearfix">
                <div class="panel-title pull-left">
                  <%= trait.capitalize %>
                </div>
              </div>
              <div class="panel-body">
                <%= render partial: "traits", object: trait, locals: { :alternative => alternative } %>
              </div>
            </div>
          </div>
        <% end %> 
      </div>
    </div>
  </div>
<% end %>



<% if @user != current_user %>
  <% content_for :right_menu do %>
    <%= render 'users/profile' %>
  <% end %>
<% else %>
    <% content_for :right_menu do %>
      <%= render 'shared/proposals' %>
    <% end %>
<% end %>