config/routes.rb
Rails.application.routes.draw do
  
  root 'alternatives#index'
  
  resources :alternatives, only: [:index, :create, :destroy]
  resources :traits
  resources :analyze
  
  resources :critical_points
  resources :requirements
  resources :evaluations
  resources :critical_evaluations

  devise_for :users, :controllers => { :registrations => "user/registrations", :sessions => "sessions", :invitations => 'invitations'  }
  get 'my_friends', to: 'users#my_friends'
  resources :users, only: [:show] do
    collection do
      get '/:id/propose_critical_points', to: 'critical_points#index', as: 'propose_critical_points'
      get '/:id/propose_requirements', to: 'requirements#index', as: 'propose_requirements'
    end
  end
    
  resources :friendships
  
  resources :requests
  
  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
      get :unread
    end
  end
  
  
  
  get 'show_proposals', to: 'proposals#show'
  
  resources :requests, only: [:index, :create]
  
  get 'welcome', to: 'welcome#start'
  
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :alternatives
  has_many :strengths
  has_many :weaknesses
  has_many :evaluations, :as => :rater
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :notifications, foreign_key: :recipient_id
  has_many :requests, foreign_key: :receiver_id
  has_many :critical_points
  has_many :requirements
  
  
  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end
  
  def self.choiso_account_id
    @choiso = User.where(first_name: "choiso").first
    return @choiso.id
  end
  
  def requests_from(user)
    requests.where(sender: user)
  end
 
  def own_alternatives
    alternatives.where(proposer_id: self.id)
  end
  
  def own_strengths
    strengths.where(proposer_id: self.id)
  end
  
  
  # Critical points
  
  def not_assigned_to(alternative, traits, proposer)
    self.send("own_#{traits}".to_sym).reject { |trait| alternative.critical_points.proposed_by(proposer).points_of_type(traits).include?(trait) }
  end
  
  def own_weaknesses
    weaknesses.where(proposer_id: self.id)
  end
  
  
  def proposals_for(showable, proposer)
    send("#{showable}".to_sym).where(proposer: proposer)
  end
  
  def proposers_of(showable)
    proposals = send("#{showable}".to_sym).where("user_id = ? AND proposer_id != ?", self.id, self.id)
    proposers = proposals.map { |trait| trait.proposer if trait.proposer }
    return proposers.uniq
  end
  
  def alternatives_proposed_for(user)
    user.alternatives.where(proposer: self)
  end
  
  def strengths_proposed_for(user)
    user.strengths.where(proposer: self)
  end
  
  def weaknesses_proposed_for(user)
    user.weaknesses.where(proposer: self)
  end

  
  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
  
  def friends_except_pending
    friends.reject { |user| user if user.created_by_invite? && !user.invitation_accepted? }
  end
  
  def except_current_user(users)
    users.reject {|user| user.id == self.id}
  end

  def self.search(param)
    return User.none if param.blank?
    
    param.strip!
    param.downcase!
    (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("lower(#{field_name}) like ?", "%#{param}%")
  end
  
  def asked_collectible_from(user, collectible)
    Request.where(sender: self, receiver: user, collectible_type: collectible).any?
  end
  
  def traits_count
    self.strengths.count + self.weaknesses.count
  end
  
end

app/views/friends/_contacts.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <div class="panel-title pull-left" style="padding-top:6px;">
      Ask your friends to propose you <span id="request-topic"><%= user_session.showable %></span>
    </div>
  </div>  
  <div class="panel-body">
    <% if current_user.friends_except_pending.count > 0 %>
      <table class="table table-striped">
        <tbody>
            <%= form_for Request.new, remote: true do |f| %>
              <% current_user.friends_except_pending.each do |friend| %>
                <tr>
                  <td><%= check_box_tag 'friend_ids[]', friend.id %></td>
                  <td><%= link_to friend.full_name, user_path(friend), class: "user-name-link" %></td>
                      <%= f.hidden_field_tag 'collectible_type', user_session.showable %>
                </tr>
              <% end %>
            </tbody>
      </table>  
      <%= f.submit 'Send request', class: "btn btn-primary" %>
      <% end %>
    <% else %>
      <h4>You haven't added any friends yet. Search friends among Choiso users or invite new.</h4>
      <br />
      <%= render 'friends/lookup' %>
    <% end %>
  </div>
</div>

app/views/friends/_inviting.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <div class="panel-title panel-title-main pull-left">
      Invite friends to help
    </div>
  </div>
  <div class="panel-body">
    <div class="form-group">
      <div class="row">
        <div class="col-md-12">
          <%= form_for [@friendship, Friendship.new], class: 'form-control search-box input-lg' do |f| %>
          <%= f.text_field :friend, placeholder: "Enter email", class: "form-control", required: true %>
        </div>
        <div class="col-md-12 form-group">
            &nbsp;
        </div>
        <div class="col-md-12">
            <%= f.submit 'Send email', class: 'btn btn btn-success' do %>
              <i class='fa fa-search'></i> Look up a friend
            <% end %>
          <% end %>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
          <%= link_to 'Invite from Facebook', root_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>  

app/views/friends/_lookup.html.erb
<div id="friend-lookup">
  <%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
    <div class="form-group">
      <div class="row">
        <div class="col-md-12">
          <%= text_field_tag :search_param, params[:search_param], placeholder: 'First Name, Last Name or Email',
                                                autofocus: true,
                                                class: 'form-control search-box input-lg' %>
        </div>
        <div class="col-md-12 form-group">
            &nbsp;
        </div>
        <div class="col-md-12">
          <%= button_tag(type: :submit, class: 'btn btn btn-success') do %>
            <i class='fa fa-search'></i> Look up a friend
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  
  <%= render 'shared/spinner' %>
  
  
  </div>
<% if @users %>
  <% if @users.size > 0 %>
    <div id="friend-lookup-results">    
      <table class="table table-striped">
        <thead>
          <tr>
            <th colspan="3" class="page-header">
              <h2>Search results</h2>
            </th>
          </tr>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.full_name %></td>
              <td><%= user.email %></td>
              <td>
                <%= link_to "View profile", user_path(user), class: "btn btn-xs btn-primary" %>
                <% if current_user.not_friends_with?(user.id) %>
                    <%= link_to "Add as my friend", add_friend_path(user: current_user, email: user.email),
                                                  class: 'btn btn-xs btn-primary', method: :post, remote: true %>
                <% else %>
                  <button class="btn btn-success btn-xs">You are friends</button>
                <% end %>
              </td>
            </tr>
          <% end %>  
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="panel-body">
      <p class="lead col-md-12">
        No people match this search criteria
      </p>
    </div>
  <% end %>
<% end %>
<div id="friend-lookup-errors"></div>

app/views/friends/_pending.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <div class="panel-title panel-title-main pull-left">
      Pending invitations
    </div>
  </div>
  <div class="panel-body">
    <% @pending_friends.each do |pfriend| %>
      <p><%= pfriend.email %></p>
    <% end %>
  </div>
</div>  

app/views/friends/create.js.erb
$('#flash-messages').html('<%= flash_messages %>');