config/routes.rb
Rails.application.routes.draw do
  
  root 'alternatives#index'
  
  resources :alternatives, only: [:index, :create, :destroy]
  resources :traits
  resources :analyze
  
  resources :critical_points
  resources :requirements
  resources :evaluations
  resources :critical_evaluations

  devise_for :users, :controllers => { :registrations => "user/registrations", :sessions => "sessions", :invitations => 'invitations'  }
  get 'my_friends', to: 'users#my_friends'
  resources :users, only: [:show] do
    collection do
      get '/:id/propose_critical_points', to: 'critical_points#index', as: 'propose_critical_points'
      get '/:id/propose_requirements', to: 'requirements#index', as: 'propose_requirements'
    end
  end
    
  resources :friendships
  
  resources :requests
  
  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
      get :unread
    end
  end
  
  
  
  get 'show_proposals', to: 'proposals#show'
  
  resources :requests, only: [:index, :create]
  
  get 'welcome', to: 'welcome#start'
  
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :alternatives
  has_many :strengths
  has_many :weaknesses
  has_many :evaluations, :as => :rater
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :notifications, foreign_key: :recipient_id
  has_many :requests, foreign_key: :receiver_id
  has_many :critical_points
  has_many :requirements
  
  
  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end
  
  def self.choiso_account_id
    @choiso = User.where(first_name: "choiso").first
    return @choiso.id
  end
  
  def requests_from(user)
    requests.where(sender: user)
  end
 
  def own_alternatives
    alternatives.where(proposer_id: self.id)
  end
  
  def own_strengths
    strengths.where(proposer_id: self.id)
  end
  
  
  # Critical points
  
  def not_assigned_to(alternative, traits, proposer)
    self.send("own_#{traits}".to_sym).reject { |trait| alternative.critical_points.proposed_by(proposer).points_of_type(traits).include?(trait) }
  end
  
  def own_weaknesses
    weaknesses.where(proposer_id: self.id)
  end
  
  
  def proposals_for(showable, proposer)
    send("#{showable}".to_sym).where(proposer: proposer)
  end
  
  def proposers_of(showable)
    proposals = send("#{showable}".to_sym).where("user_id = ? AND proposer_id != ?", self.id, self.id)
    proposers = proposals.map { |trait| trait.proposer if trait.proposer }
    return proposers.uniq
  end
  
  def alternatives_proposed_for(user)
    user.alternatives.where(proposer: self)
  end
  
  def strengths_proposed_for(user)
    user.strengths.where(proposer: self)
  end
  
  def weaknesses_proposed_for(user)
    user.weaknesses.where(proposer: self)
  end

  
  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
  
  def friends_except_pending
    friends.reject { |user| user if user.created_by_invite? && !user.invitation_accepted? }
  end
  
  def except_current_user(users)
    users.reject {|user| user.id == self.id}
  end

  def self.search(param)
    return User.none if param.blank?
    
    param.strip!
    param.downcase!
    (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("lower(#{field_name}) like ?", "%#{param}%")
  end
  
  def asked_collectible_from(user, collectible)
    Request.where(sender: self, receiver: user, collectible_type: collectible).any?
  end
  
  def traits_count
    self.strengths.count + self.weaknesses.count
  end
  
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters
  skip_before_action :require_login
  
  def after_inactive_sign_up_path_for(resource)
    root_path
  end
  
  def after_sign_up_path_for(resource)
    root_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name)
    devise_parameter_sanitizer.for(:account_update).push(:first_name, :last_name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def my_friends
    @friendships = current_user.friends_except_pending
    @pending_friends = current_user.friends.invitation_not_accepted
  end
  
  def search
    @users = User.search(params[:search_param])
    
    if @users
      @users = current_user.except_current_user(@users)
      render partial: 'friends/lookup'
    else
      render status: :not_found, nothing: true
    end
  end

  def add_friend
    @friend = User.invite!(email: params[:email])
    current_user.friendships.build(friend_id: @friend.id)
    
    if current_user.save
      #redirect_to my_friends_path, notice: "Friend was successfully added / invited."
      respond_to do |format|
        format.js
      end
    else
      redirect_to my_friends_path, flash[:error] = "There was an error with adding user as friend. Fuck knows why. :("
    end
  end
  
  def show
    @user = User.find(params[:id])
    @resources = ["Alternative", "Strength", "Weakness"]    
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def folder_name_for(resource)
    case resource
      when "Strength", "Weakness"
        "traits"
      else
        resource.downcase.pluralize
    end
  end
end

app/views/users/_profile.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="well">
      <div class="text-center">
        <%= gravatar_for @user, size: 150 %>
      </div>
      <div class="text-center">
        <h3><%= @user.full_name %></h3>
      </div>
      <div class="text-center">
        <% if current_user.not_friends_with?(@user.id) %>
          <%= link_to "Add as my friend", add_friend_path(user: current_user, friend: @user),
                                                      class: 'btn btn-primary', method: :post, remote: true %>
        <% else %>
          <span class="label label-success">You are friends</span>
        <% end %>
      </div>  
    </div>    
  </div>
</div>  

app/views/users/add_friend.js.erb
$('#flash-messages').html('<%= flash_messages %>');

app/views/users/my_friends.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading clearfix">
        <div class="panel-title panel-title-main pull-left">
          My friends
        </div>
      </div>  
      <% if @friendships.size > 0 %>
        <table class="table">
      <tbody>
          <% @friendships.each do |friend| %>
            <tr>
              <td><%= gravatar_for friend, size: 50 %></td>
              <td>
                <%= link_to friend.full_name, user_path(friend), class: "user-name-link" %>
              </td>
              <td><%= friend.email %></td>
              <td>
                <%= link_to "View Profile", user_path(friend), class: "btn btn-primary btn-xs" %>
                <%= link_to 'Remove Friend', friendship_path(friend), :method => :delete,
                                            :data => { :confirm => 'Are you sure?' },
                                            :class => 'btn btn-xs btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
        <div class='panel-body'>
          <p class="lead text-center">You don't have any friends yet. Please add some!</p>
        </div>
      <% end %>  
    </div>
  </div>
</div>  

<%= content_for :right_menu do %>
  <%= render 'friends/inviting' %>
  <%= render 'friends/pending' %>
<% end %>  

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading clearfix">
        <div class="panel-title panel-title-main pull-left">
          Search for friends registred in Choiso
        </div>
      </div>  
      <div class="panel-body">   
        <%= render 'friends/lookup' %>
      </div>
    </div>
  </div>
</div>  

app/views/users/show.html.erb
<div class="row">
  <% @resources.each do |resource| %>
    <% if @user.asked_collectible_from(current_user, resource) %>
      <%= render partial: "#{folder_name_for(resource)}/block", locals: { :resource => resource } %>
    <% end %>
  <% end %>  
</div>

<% content_for :right_menu do %>
  <%= render 'users/profile' %>
  <div class="row">
    <div class="col-md-12 text-center">
      <%= link_to 'Propose critical points', propose_critical_points_users_path(:proposer_id => @user.id), class: "btn btn-success" %>
    </div>
    <div class="col-md-12 text-center">
      <%= link_to 'Propose requirements', propose_requirements_users_path(:proposer_id => @user.id), class: "btn btn-success" %>
    </div>
  </div>
<% end %>