config/routes.rb
Rails.application.routes.draw do
  
  root 'alternatives#index'
  
  resources :alternatives, only: [:index, :create, :destroy]
  resources :traits
  resources :analyze
  
  resources :critical_points
  resources :requirements
  resources :evaluations
  resources :critical_evaluations

  devise_for :users, :controllers => { :registrations => "user/registrations", :sessions => "sessions", :invitations => 'invitations'  }
  get 'my_friends', to: 'users#my_friends'
  resources :users, only: [:show] do
    collection do
      get '/:id/propose_critical_points', to: 'critical_points#index', as: 'propose_critical_points'
      get '/:id/propose_requirements', to: 'requirements#index', as: 'propose_requirements'
    end
  end
    
  resources :friendships
  
  resources :requests
  
  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
      get :unread
    end
  end
  
  
  
  get 'show_proposals', to: 'proposals#show'
  
  resources :requests, only: [:index, :create]
  
  get 'welcome', to: 'welcome#start'
  
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
  
  

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
  belongs_to :evaluable, polymorphic: true
  belongs_to :collectible, polymorphic: true
  
  def already_exists?
    Request.exists?(:receiver_id => self.receiver_id, 
                    :sender_id => self.sender_id, :evaluable_id => self.evaluable_id, 
                    :collectible_id => self.collectible_id)
  end
  
  def send_to(friend_id)
    self.receiver = User.find(friend_id)
    self.save unless self.already_exists?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :alternatives
  has_many :strengths
  has_many :weaknesses
  has_many :evaluations, :as => :rater
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :notifications, foreign_key: :recipient_id
  has_many :requests, foreign_key: :receiver_id
  has_many :critical_points
  has_many :requirements
  
  
  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end
  
  def self.choiso_account_id
    @choiso = User.where(first_name: "choiso").first
    return @choiso.id
  end
  
  def requests_from(user)
    requests.where(sender: user)
  end
 
  def own_alternatives
    alternatives.where(proposer_id: self.id)
  end
  
  def own_strengths
    strengths.where(proposer_id: self.id)
  end
  
  
  # Critical points
  
  def not_assigned_to(alternative, traits, proposer)
    self.send("own_#{traits}".to_sym).reject { |trait| alternative.critical_points.proposed_by(proposer).points_of_type(traits).include?(trait) }
  end
  
  def own_weaknesses
    weaknesses.where(proposer_id: self.id)
  end
  
  
  def proposals_for(showable, proposer)
    send("#{showable}".to_sym).where(proposer: proposer)
  end
  
  def proposers_of(showable)
    proposals = send("#{showable}".to_sym).where("user_id = ? AND proposer_id != ?", self.id, self.id)
    proposers = proposals.map { |trait| trait.proposer if trait.proposer }
    return proposers.uniq
  end
  
  def alternatives_proposed_for(user)
    user.alternatives.where(proposer: self)
  end
  
  def strengths_proposed_for(user)
    user.strengths.where(proposer: self)
  end
  
  def weaknesses_proposed_for(user)
    user.weaknesses.where(proposer: self)
  end

  
  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
  
  def friends_except_pending
    friends.reject { |user| user if user.created_by_invite? && !user.invitation_accepted? }
  end
  
  def except_current_user(users)
    users.reject {|user| user.id == self.id}
  end

  def self.search(param)
    return User.none if param.blank?
    
    param.strip!
    param.downcase!
    (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("lower(#{field_name}) like ?", "%#{param}%")
  end
  
  def asked_collectible_from(user, collectible)
    Request.where(sender: self, receiver: user, collectible_type: collectible).any?
  end
  
  def traits_count
    self.strengths.count + self.weaknesses.count
  end
  
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!
    
    def index
      respond_to do |format|
        format.js
      end
    end
    
    
    def create
      params[:friend_ids].each do |friend_id|
        @request = Request.new(request_params)
        @request.send_to(friend_id)
      
        #Create notification
        Notification.generate("asked", @request)
      end
      
      respond_to do |format|
        format.js { flash.now[:success] = "Request was successfully submitted" }
      end      
    end
  
  
  private
  
  def request_params
    params.require(:request).permit(:sender_id, :collectible_id, :collectible_type, :evaluable_id, :evaluable_type)
  end
    
end

app/views/requests/_collectible.html.erb
<div class="panel-heading clearfix">
  <div class="panel-title pull-left" style="padding-top:6px;">
    Ask your friends to propose you <span id="request-topic"><%= user_session.showable %></span>
  </div>
</div>  
<div class="panel-body">
  <% if current_user.friends_except_pending.count > 0 %>
    <%= form_for Request.new, remote: true do |f| %>
      <%= f.hidden_field :collectible_id, :value => collectible.id %>
      <%= f.hidden_field :collectible_type, :value => collectible.class %>
      <%= f.hidden_field :sender_id, :value => current_user.id %>
      <table class="table table-striped">
        <tbody>
          <% current_user.friends_except_pending.each do |friend| %>
            <tr>
              <td><%= check_box_tag 'friend_ids[]', friend.id %></td>
              <td><%= link_to friend.full_name, user_path(friend), class: "user-name-link" %>
                <% if current_user.asked_collectible_from(friend, collectible.class) %>
                  <span class="label label-success">Request sent</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>  
      <%= f.submit 'Send request', class: "btn btn-primary" %>
    <% end %>
  <% else %>
    <h4 class="text-center">You haven't added any friends yet. Search friends among Choiso users or invite new.</h4>
    <br />
    <div class="text-center">
      <%= link_to 'Add friends', my_friends_path, class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/requests/create.js.erb
$('#flash-messages').html('<%= flash_messages %>');
$("#new_request")[0].reset();

app/views/requests/index.js.erb
$('#collectible').html('<%= j render partial: 'requests/collectible', object: user_session.collectible %>');